### ISSUE TITLE
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters

### ISSUE THREAD

**Issue by wpaven** [scylladb/scylla-migrator#138]
Ran into this issue running build steps (first 3 steps of Building in the README)  in ubuntu 22.04 docker container.  

Build will error out with:
`[error] java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: shapeless/$tilde$qmark$greater$λ.class`

We were able to build running `git reset --hard c8a05d3` on the project before running build.sh So is it something in the latest master that requires updating? Or a documentation issue? (Do we need to explicitly set UTF-* encoding for the env?)

Build output attached. 
[build-output.txt.zip](https://github.com/scylladb/scylla-migrator/files/15254827/build-output.txt.zip)

**Comment by tarzanek** [comment]
you need to `sbt clean` if you switch too much around, likely that was the problem, but let me check the output

**Comment by julienrf** [comment]
Was this problem fixed?

**Comment by tarzanek** [comment]
yes, closing , binary release fixes such issues
