### ISSUE TITLE
add support for assume role for s3 access to parquet files

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-migrator#149]
we should add an option to assume role for s3 access , which is defacto standard these days

It should be as easy as
https://medium.com/@leythg/access-s3-using-pyspark-by-assuming-an-aws-role-9558dbef0b9e
(of course rewritten to scala and proper input properties exposed in config file)

**Comment by tarzanek** [comment]
fwiw we should be able to use above in other s3 cases too, ev. for DynamoDB too

**Comment by julienrf** [comment]
PR #150 only fixed the issue for DynamoDB, not for Parquet files.

**Comment by guy9** [comment]
Thanks @julienrf , please proceed with upgrading the Hadoop and Spark versions.
