### ISSUE TITLE
$SPARK_HOME/work can fill up on worker nodes during DynamoDB S3 export migration

### ISSUE THREAD

**Issue by GeoffMontee** [scylladb/scylla-migrator#189]
This is similar to issue #167, but it impacts migrations from DynamoDB S3 exports, rather than migrations from DynamoDB.

It appears that `/opt/spark/work` can fill up on worker nodes.

**Comment by GeoffMontee** [comment]
It looks like `/opt/spark/work` is being filled with thousands of copies of `scylla-migrator-assembly.jar`, which causes the disk to fill up.

**Comment by tarzanek** [comment]
@GeoffMontee how do you submit the job?
What is the spark cluster info?

**Comment by julienrf** [comment]
After investigating the problem internally, we found out that it was caused by a misconfiguration of the Spark cluster. I’ve created #191 as a follow-up.
