### ISSUE TITLE
Improve documentation regarding the correct way to submit the Spark job

### ISSUE THREAD

**Issue by julienrf** [scylladb/scylla-migrator#191]
When the Spark cluster is not correctly sized, or when the migrator is not invoked with the correct `--executor-memory` / `--executor-cores` parameters, users may experience hard to debug failures such as #189.

Currently, we do provide some information about the Spark cluster configuration.

In section [Set Up a Spark Cluster](https://migrator.docs.scylladb.com/stable/getting-started/index.html#set-up-a-spark-cluster):

> A Spark cluster is made of several _nodes_, which can contain several _workers_ (although there is usually just one worker per node). When you start the Migrator, the Spark _driver_ looks at the job content and splits it into tasks. It then spawns _executors_ on the cluster workers and feed them with the tasks to compute.
>
> We recommend provisioning at least 2 GB of memory per CPU on each node. For instance, a cluster node with 4 CPUs should have at least 8 GB of memory.

And, in section [Run the Migration](https://migrator.docs.scylladb.com/stable/getting-started/index.html#run-the-migration):

> We recommend using between 5 to 10 CPUs per Spark executor. For instance, if your Spark worker node has 16 CPUs, you could use 8 CPUs per executor (the Spark driver would then allocate two executors on the worker to fully utilize its resources). You can control the number of CPUs per executors with the argument `--executor-cores` passed to the `spark-submit` command:
>
>     --executor-cores 8
>
> We also recommend using 2 GB of memory per CPU. So, if you provide 8 CPU per executor, you should require 16 GB of memory on the executor. You can control the amount of memory per executor with the argument `--executor-memory` passed to the `spark-submit` command:
>
>     --executor-memory 16G

However, this information is often missed by the users.

Instead, we should insist, on every page that describes how to set up a Spak cluster ([with Ansible](https://migrator.docs.scylladb.com/stable/getting-started/ansible.html), [manually](https://migrator.docs.scylladb.com/stable/getting-started/spark-standalone.html), with [AWS EMR](https://migrator.docs.scylladb.com/stable/getting-started/aws-emr.html), or with [Docker](https://migrator.docs.scylladb.com/stable/getting-started/docker.html)), that correctly sizing the cluster and invoking `spark-submit` with the correct arguments is important, and we should provide direct links to the corresponding documentation sections.

**Comment by guy9** [comment]
Thanks @julienrf .
@GeoffMontee , @tarzanek , @pdbossman please have a look and add any input you might have.

**Comment by guy9** [comment]
@julienrf please proceed with your suggestion
