### ISSUE TITLE
Docs: set multi version releases with 1.0 is stable

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-migrator#203]
See https://sphinx-theme.scylladb.com/stable/configuration/multiversion.html for more

**Comment by julienrf** [comment]
@dgarcia360 How do we define the branch name to display? I see that [here](https://github.com/scylladb/sphinx-scylladb-theme/blob/25364e88acd11b835c21a134077f9ecec9b57d4a/docs/source/conf.py#L16) you use `branch-1.7` as a branch name, but when the website is rendered it is displayed as `1.7` only.

**Comment by julienrf** [comment]
Closed by c6f46806d2fc08ca92a0f2e4cb2646da223bfd69
