### ISSUE TITLE
decimal type migrations showing different results

### ISSUE THREAD

**Issue by sangeethdba** [scylladb/scylla-migrator#33]
we see issues with scylla-migrator while handling decimals. for example my source columns with type decimal has data as 11 and after migration the target table data showing as 11.00000000000000

table defination has 

    availability decimal,

source :

availability

11

target:

availability

11.000000000000000000

what need to done ,to see same data  in both source and target

**Comment by sangeethdba** [comment]
any thing to do with floatingPointTolerance ?

**Comment by sangeethdba** [comment]
@iravid

**Comment by sangeethdba** [comment]
CREATE TABLE qa2.iav (
    ktu int,
    lid text,
    lt text,
    av decimal,
    adsq decimal,
    bq bigint,
    mts timestamp,
    mu text,
    uav decimal,
    PRIMARY KEY ((ktu, lid, lt))
) WITH bloom_filter_fp_chance = 0.1
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}


source
**
 ktu        | lid | lt | av | adsq | bq |  mts                                     |                                                                mu                      | uav
------------+-------------+---------------+--------------+-----------------------------+-----------------+---------------------------------+-------------------------+-------------------------
 123456 |        321 |           xyz |            0 |                         null |            null | 2020-06-23 13:43:16.092000-0400 | test |                       0
 ktu        | lid | lt | av | adsq | bq | mts                       | mu             | uav
--------+-------------+---------------+--------------+------------------------------+-----------------+---------------------------------+-------------------------+-------------------------
 34567 |        543 |           qwer |           11 |                     0.176871 |               0 | 2020-08-14 17:55:15.208000-0400 | loader |                      12


target*

 ktu        | lid | lt | av | adsq | bq | mts                       | mu             | uav
------------+-------------+---------------+--------------+------------------------------+-----------------+---------------------------------+-------------------------+-------------------------
 123456 |        321 |           xyz |        0E-18 |                         null |            null | 2020-06-23 17:43:16.092000+0000 | test |                   0E-18
 
 ktu        | lid | lt | av | adsq | bq | mts                       | mu             | uav
--------+-------------+---------------+-----------------------+------------------------------+-----------------+---------------------------------+-------------------------+-------------------------
 34567 |        543 |           qwer | 11.000000000000000000 |         0.176871000000000000 |               0 | 2020-08-14 21:55:15.208000+0000 | loader|   12.000000000000000000


    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.DeflateCompressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';


source data:

**Comment by sangeethdba** [comment]
@iravid  FYI

**Comment by sangeethdba** [comment]
@iravid can you hep

**Comment by sangeethdba** [comment]
any help is apprecaited

**Comment by iravid** [comment]
Hi @sangeethdba - please pull the latest master version and add stripTrailingZerosForDecimals: true to the target section of your config.yaml . That should solve the issue.
