### ISSUE TITLE
Add SSL support for the spark-cassandra connector in the migrator

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla-migrator#9]
Users would like to enable SSL connection between the migrator connections and Cassandra and Scylla. 
We would like to make sure we have the needed support, similar to:
https://www.instaclustr.com/support/documentation/cassandra-add-ons/apache-spark/instaclustr-spark-with-ssl-configured-cassandra-cluster/

**Comment by tarzanek** [comment]
https://ultrabug.fr/Tech%20Blog/2018/2018-07-19-authenticating-and-connecting-to-a-ssl-enabled-scylla-cluster-using-spark-2/
and https://ultrabug.fr/Tech%20Blog/2020/2020-11-06-renaming-and-reshaping-scylla-tables-using-scylla-migrator/
is working
so this just needs documentation similar to above blogs

**Comment by tarzanek** [comment]
https://github.com/scylladb/scylla-migrator/commit/f52bea9832a318d1539c46c447e1733043806593
should fix it, testing now

**Comment by tarzanek** [comment]
fixed by https://github.com/scylladb/scylla-migrator/pull/49
