### ISSUE TITLE
Can we use this to copy data from Scylladb to Cassandra

### ISSUE THREAD

**Issue by rahulJuspay** [scylladb/scylla-migrator#94]
I want to check if this service can migrate data from Scylladb to Cassandra??

**Comment by tarzanek** [comment]
@rahulJuspay it definitely can, more in readme:
https://github.com/scylladb/scylla-migrator/blob/master/README.md

or check the demo on https://github.com/scylladb/scylla-code-samples/tree/master/spark-scylla-migrator-demo

if you need spark 3.x version, it can be found in https://github.com/scylladb/scylla-migrator/tree/spark-3.1.1
