### ISSUE TITLE
Migrator does not create Indexes based on DynamoDB table

### ISSUE THREAD

**Issue by hopugop** [scylladb/scylla-migrator#99]
When inferring schema from base DynamoDB table, Migrator skips indexes creation. Indexes cannot be created after the fact, so users have to resort to manually create the schema + indexes prior migrating.
Migrator should create Indexes along the base table, so they are properly populated.

**Comment by julienrf** [comment]
Indexes should be available from the output of [describe-table](https://docs.aws.amazon.com/cli/latest/reference/dynamodb/describe-table.html#output). We should be able to use that information to re-create the indexes on the target table.

**Comment by julienrf** [comment]
While working on this, I hit https://github.com/scylladb/scylladb/issues/19716 which makes it difficult to check whether the schema of a table has been correctly replicated or not.

**Comment by tarzanek** [comment]
* Note
once Scylla supports https://github.com/scylladb/scylladb/issues/11567 we can then have configurable switch to copy indexes later, until then we will just sync them together with data
